Feat/login
ngomy2001/BookStoreProject pull request #8
Opened 2023-03-21 09:19 UTC by ngomy2001

2023-03-22 03:12 UTC, voquanghoa commented on src/main/java/com/example/bookstoreproject/domain/auths/JwtTokenService.java
> +                UUID.fromString(claims.get(CLAIM_USER_ID).toString()),
Tạo biến và kiểm tra như trên

2023-03-22 03:12 UTC, voquanghoa commented on src/main/java/com/example/bookstoreproject/domain/auths/JwtUserDetailsService.java
> +                .orElseThrow(() -> new UsernameNotFoundException("User not found with username: " + username));
Tạo suply

```suggestion
                .orElseThrow(() -> new UsernameNotFoundException("User not found with username: %s", username));
```

2023-03-22 03:12 UTC, voquanghoa commented on src/main/java/com/example/bookstoreproject/persistence/role/RoleStore.java
> +    public String getRoleById(final UUID uuid) {
Tích hợp với real database

2023-03-22 03:12 UTC, voquanghoa commented on src/test/java/com/example/bookstoreproject/api/AbstractControllerTest.java
> +        return perform(MockMvcRequestBuilders.delete(url).with(csrf()).contentType(MediaType.APPLICATION_JSON));
Mấy thay đổi này thực hiện ở hàm perform

2023-03-22 03:12 UTC, voquanghoa commented on src/test/java/com/example/bookstoreproject/api/WithMockUserSecurityContextFactory.java
> +        final Authentication auth = new UserAuthenticationToken(UUID.fromString("d222d1e5-ab31-441b-be90-e74ce7cd32dd"), "user", List.of(new SimpleGrantedAuthority("ROLE_USER")));
Gọi hàm buildContributor, role Contributor chứ

2023-03-22 03:12 UTC, voquanghoa commented on src/test/java/com/example/bookstoreproject/api/WithMockAdminSecurityContextFactory.java
> +        final Authentication auth = new UserAuthenticationToken(
Gọi hàm buildAdmin

2023-03-22 03:19 UTC, ngomy2001 commented on src/main/java/com/example/bookstoreproject/domain/auths/JwtTokenService.java
> +                UUID.fromString(claims.get(CLAIM_USER_ID).toString()),
DONE

2023-03-22 03:36 UTC, ngomy2001 commented on src/main/java/com/example/bookstoreproject/domain/auths/JwtUserDetailsService.java
> +                .orElseThrow(() -> new UsernameNotFoundException("User not found with username: " + username));
DONE

2023-03-22 07:27 UTC, ngomy2001 commented on src/main/java/com/example/bookstoreproject/persistence/role/RoleStore.java
> +    public String getRoleById(final UUID uuid) {
DONE

2023-03-22 07:31 UTC, ngomy2001 commented on src/test/java/com/example/bookstoreproject/api/AbstractControllerTest.java
> +        return perform(MockMvcRequestBuilders.delete(url).with(csrf()).contentType(MediaType.APPLICATION_JSON));
DONE

2023-03-22 08:32 UTC, ngomy2001 commented on src/test/java/com/example/bookstoreproject/api/WithMockUserSecurityContextFactory.java
> +        final Authentication auth = new UserAuthenticationToken(UUID.fromString("d222d1e5-ab31-441b-be90-e74ce7cd32dd"), "user", List.of(new SimpleGrantedAuthority("ROLE_USER")));
DONE

2023-03-22 08:32 UTC, ngomy2001 commented on src/test/java/com/example/bookstoreproject/api/WithMockAdminSecurityContextFactory.java
> +        final Authentication auth = new UserAuthenticationToken(
DONE

2023-03-23 10:34 UTC, voquanghoa commented on src/main/java/com/example/bookstoreproject/persistence/role/RoleEntityMapper.java
> +    public static List<Role> toRoles(final List<RoleEntity> roleEntities) {
Cái này không cần

2023-03-23 10:34 UTC, voquanghoa commented on src/main/java/com/example/bookstoreproject/persistence/role/RoleEntityMapper.java
> +    public static RoleEntity toRoleEntity(final Role role) {
Chắc mình không cần cái này đâu

2023-03-23 10:34 UTC, voquanghoa commented on src/main/java/com/example/bookstoreproject/persistence/role/RoleStore.java
> +        return toRole(roleRepository.findById(id).orElseThrow(null));
Mình trả về Optional ở đây, không throw exception

2023-03-23 10:34 UTC, voquanghoa commented on src/test/java/com/example/bookstoreproject/fakes/AuthFakes.java
> +    public static Authentication buildAuth() {
```suggestion

    public static Authentication buildAuthentication() {
```

2023-03-23 10:34 UTC, voquanghoa commented on src/test/java/com/example/bookstoreproject/fakes/AuthFakes.java
> +        JwtUserDetails userDetails = new JwtUserDetails(
```suggestion
        final JwtUserDetails userDetails = new JwtUserDetails(
```

2023-03-23 10:34 UTC, voquanghoa commented on src/main/java/com/example/bookstoreproject/api/profile/ProfileController.java
> +    public UserDTO update(final @PathVariable UUID id, final @RequestBody UserDTO userDTO) {
Đã bảo là current user rồi mà còn truyền id

2023-03-24 02:47 UTC, ngomy2001 commented on src/main/java/com/example/bookstoreproject/persistence/role/RoleEntityMapper.java
> +    public static List<Role> toRoles(final List<RoleEntity> roleEntities) {
DONE

2023-03-24 02:47 UTC, ngomy2001 commented on src/main/java/com/example/bookstoreproject/persistence/role/RoleEntityMapper.java
> +    public static RoleEntity toRoleEntity(final Role role) {
DONE

2023-03-24 03:03 UTC, ngomy2001 commented on src/main/java/com/example/bookstoreproject/persistence/role/RoleStore.java
> +        return toRole(roleRepository.findById(id).orElseThrow(null));
DONE

2023-03-24 03:05 UTC, ngomy2001 commented on src/test/java/com/example/bookstoreproject/fakes/AuthFakes.java
> +    public static Authentication buildAuth() {
DONE

2023-03-24 03:05 UTC, ngomy2001 commented on src/test/java/com/example/bookstoreproject/fakes/AuthFakes.java
> +        JwtUserDetails userDetails = new JwtUserDetails(
DONE

2023-03-24 03:11 UTC, ngomy2001 commented on src/main/java/com/example/bookstoreproject/api/profile/ProfileController.java
> +    public UserDTO update(final @PathVariable UUID id, final @RequestBody UserDTO userDTO) {
DONE

2023-03-24 03:41 UTC, voquanghoa commented on src/main/java/com/example/bookstoreproject/api/profile/ProfileController.java
> +    public UserDTO findById(@PathVariable UUID id) {
Bỏ id

2023-03-24 03:42 UTC, voquanghoa commented on src/main/java/com/example/bookstoreproject/domain/user/UserService.java
> +    }
id phải được truyền từ controller sang (và bỏ hàm này)

2023-03-24 04:12 UTC, ngomy2001 commented on src/main/java/com/example/bookstoreproject/api/profile/ProfileController.java
> +    public UserDTO findById(@PathVariable UUID id) {
DONE

2023-03-24 04:12 UTC, ngomy2001 commented on src/main/java/com/example/bookstoreproject/domain/user/UserService.java
> +    }
DONE

2023-03-24 04:26 UTC, voquanghoa commented on src/main/java/com/example/bookstoreproject/error/AccessDeniedException.java
> +    public AccessDeniedException(String message, Object... args) { super(HttpStatus.FORBIDDEN, message, args);}
```suggestion
    public AccessDeniedException(String message, Object... args) { 
                  super(HttpStatus.FORBIDDEN, message, args);
    }
```

2023-03-24 04:26 UTC, voquanghoa commented on src/main/java/com/example/bookstoreproject/error/AccessDeniedException.java
> +public class AccessDeniedException extends DomainException{
```suggestion
public class ForbiddenException extends DomainException{
```

2023-03-24 04:27 UTC, ngomy2001 commented on src/main/java/com/example/bookstoreproject/error/AccessDeniedException.java
> +    public AccessDeniedException(String message, Object... args) { super(HttpStatus.FORBIDDEN, message, args);}
DONE

2023-03-24 04:28 UTC, ngomy2001 commented on src/main/java/com/example/bookstoreproject/error/AccessDeniedException.java
> +public class AccessDeniedException extends DomainException{
DONE

2023-03-27 09:40 UTC, nguyenvanman requested changes

2023-03-27 09:40 UTC, nguyenvanman commented on src/main/java/com/example/bookstoreproject/domain/auths/JwtUserDetailsService.java
> +                .map(user -> buildUser(toUserEntity(user)))
Vì sao lại toUserEntity ở đây?

2023-03-27 09:41 UTC, ngomy2601 commented on src/main/java/com/example/bookstoreproject/domain/auths/JwtUserDetailsService.java
> +                .map(user -> buildUser(toUserEntity(user)))
Em updated roi a

2023-03-27 09:52 UTC, nguyenvanman requested changes

2023-03-27 09:52 UTC, nguyenvanman commented on build.gradle
> +    implementation 'com.cloudinary:cloudinary-http44:1.33.0'
Cái này không liên quan tới login đúng không?

2023-03-27 09:52 UTC, nguyenvanman commented on src/main/java/com/example/bookstoreproject/api/auth/AuthController.java
> +@RequestMapping("api/v1/auths")
```suggestion
@RequestMapping("api/v1/auth")
```

2023-03-27 09:52 UTC, nguyenvanman commented on src/main/java/com/example/bookstoreproject/configuration/JwtTokenAuthorizationFilter.java
> +public class JwtTokenAuthorizationFilter extends OncePerRequestFilter {
```suggestion
public class JwtRequestFilter extends OncePerRequestFilter {
```

JWT = JSON Web Token, không cần suffix nó với Token nữa

2023-03-27 09:58 UTC, ngomy2001 commented on build.gradle
> +    implementation 'com.cloudinary:cloudinary-http44:1.33.0'
Da dung

2023-03-28 10:25 UTC, merged